// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvHWXf5QfJePkE94IEpChJeY8akWUPvRo',
    appId: '1:393057096443:web:99d5eae21c5f2a81bed65e',
    messagingSenderId: '393057096443',
    projectId: 'instagram-clone-896c2',
    authDomain: 'instagram-clone-896c2.firebaseapp.com',
    storageBucket: 'instagram-clone-896c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMKivF4p84fFg6nHKU_JbHkHIOzai-1lQ',
    appId: '1:393057096443:android:73850bda0fbd06fbbed65e',
    messagingSenderId: '393057096443',
    projectId: 'instagram-clone-896c2',
    storageBucket: 'instagram-clone-896c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLDOkKG12bxc5q48CnQ59ILFWeobcr9o4',
    appId: '1:393057096443:ios:efc8754b806393a8bed65e',
    messagingSenderId: '393057096443',
    projectId: 'instagram-clone-896c2',
    storageBucket: 'instagram-clone-896c2.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLDOkKG12bxc5q48CnQ59ILFWeobcr9o4',
    appId: '1:393057096443:ios:efc8754b806393a8bed65e',
    messagingSenderId: '393057096443',
    projectId: 'instagram-clone-896c2',
    storageBucket: 'instagram-clone-896c2.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvHWXf5QfJePkE94IEpChJeY8akWUPvRo',
    appId: '1:393057096443:web:e8f46b562e2b5d1fbed65e',
    messagingSenderId: '393057096443',
    projectId: 'instagram-clone-896c2',
    authDomain: 'instagram-clone-896c2.firebaseapp.com',
    storageBucket: 'instagram-clone-896c2.appspot.com',
  );
}
